import type { LevelConfig } from '../types';

/**
 * 16 branchy mazes for a sharp ~7-year-old.
 *
 * Growing-tree generation (high random-pick) produces many junctions and
 * cul-de-sacs — not the old long guided corridor. Every level is
 * single-width (widenPasses: 0). Goal is the farthest cell.
 *
 * Seeds were scored for dead ends + solution-path choice points.
 * Late levels add sparse opposite-wall loops only (never open rooms).
 */
export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Meadow Trek',
    rows: 17,
    cols: 17,
    seed: 15457,
    difficulty: 'easy',
    theme: 'meadow',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 2,
    name: 'Hedge Hunt',
    rows: 17,
    cols: 19,
    seed: 15345,
    difficulty: 'easy',
    theme: 'hedge',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 3,
    name: 'Orchard Twist',
    rows: 19,
    cols: 19,
    seed: 1225,
    difficulty: 'easy',
    theme: 'orchard',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 4,
    name: 'River Bend',
    rows: 19,
    cols: 21,
    seed: 3645,
    difficulty: 'easy',
    theme: 'river',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 5,
    name: 'Forest Fork',
    rows: 21,
    cols: 21,
    seed: 12757,
    difficulty: 'easy',
    theme: 'forest',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 6,
    name: 'Canyon Crawl',
    rows: 21,
    cols: 21,
    seed: 15005,
    difficulty: 'medium',
    theme: 'canyon',
    widenPasses: 0,
    loopCount: 1,
  },
  {
    id: 7,
    name: 'Sunset Switchback',
    rows: 21,
    cols: 23,
    seed: 15105,
    difficulty: 'medium',
    theme: 'sunset',
    widenPasses: 0,
    loopCount: 1,
  },
  {
    id: 8,
    name: 'Tide Pools',
    rows: 23,
    cols: 23,
    seed: 5585,
    difficulty: 'medium',
    theme: 'tide',
    widenPasses: 0,
    loopCount: 2,
  },
  {
    id: 9,
    name: 'Crystal Cave',
    rows: 23,
    cols: 23,
    seed: 11597,
    difficulty: 'medium',
    theme: 'crystal',
    widenPasses: 0,
    loopCount: 2,
  },
  {
    id: 10,
    name: 'Lava Labyrinth',
    rows: 23,
    cols: 25,
    seed: 10593,
    difficulty: 'medium',
    theme: 'lava',
    widenPasses: 0,
    loopCount: 2,
  },
  {
    id: 11,
    name: 'Storm Spiral',
    rows: 25,
    cols: 25,
    seed: 4377,
    difficulty: 'hard',
    theme: 'storm',
    widenPasses: 0,
    loopCount: 3,
  },
  {
    id: 12,
    name: 'Aurora Alley',
    rows: 25,
    cols: 25,
    seed: 3253,
    difficulty: 'hard',
    theme: 'aurora',
    widenPasses: 0,
    loopCount: 3,
  },
  {
    id: 13,
    name: 'Moon Maze',
    rows: 25,
    cols: 25,
    seed: 2225,
    difficulty: 'hard',
    theme: 'moon',
    widenPasses: 0,
    loopCount: 3,
  },
  {
    id: 14,
    name: 'Dragon Den',
    rows: 25,
    cols: 25,
    seed: 5089,
    difficulty: 'hard',
    theme: 'dragon',
    widenPasses: 0,
    loopCount: 4,
  },
  {
    id: 15,
    name: 'Galaxy Gate',
    rows: 25,
    cols: 25,
    seed: 761,
    difficulty: 'hard',
    theme: 'galaxy',
    widenPasses: 0,
    loopCount: 4,
  },
  {
    id: 16,
    name: 'Champion Cup',
    rows: 25,
    cols: 25,
    seed: 4157,
    difficulty: 'hard',
    theme: 'champion',
    widenPasses: 0,
    loopCount: 5,
  },
];

export function getLevel(id: number): LevelConfig | undefined {
  return LEVELS.find((l) => l.id === id);
}
