import type { LevelConfig } from '../types';

/**
 * 16 real mazes for a sharp ~7-year-old player.
 *
 * Every level is a single-width recursive-backtracker maze (widenPasses: 0).
 * Early boards are already 15–19 odd, with long farthest-cell solutions and
 * lots of dead ends — not the old 7×7 wide-path starters.
 *
 * Mid/late boards grow toward 21–25 so they still fit an iPad Mini with
 * readable cells. A few later levels add sparse opposite-wall loops
 * (loopCount) for interest, never open rooms.
 *
 * Seeds were picked for branchiness + long solution path and are deterministic.
 */
export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Meadow Trek',
    rows: 15,
    cols: 15,
    seed: 6560,
    difficulty: 'easy',
    theme: 'meadow',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 2,
    name: 'Hedge Hunt',
    rows: 15,
    cols: 17,
    seed: 3542,
    difficulty: 'easy',
    theme: 'hedge',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 3,
    name: 'Orchard Twist',
    rows: 17,
    cols: 17,
    seed: 2405,
    difficulty: 'easy',
    theme: 'orchard',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 4,
    name: 'River Bend',
    rows: 17,
    cols: 19,
    seed: 4298,
    difficulty: 'easy',
    theme: 'river',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 5,
    name: 'Forest Fork',
    rows: 19,
    cols: 19,
    seed: 4217,
    difficulty: 'easy',
    theme: 'forest',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 6,
    name: 'Canyon Crawl',
    rows: 19,
    cols: 21,
    seed: 71,
    difficulty: 'medium',
    theme: 'canyon',
    widenPasses: 0,
    loopCount: 1,
  },
  {
    id: 7,
    name: 'Sunset Switchback',
    rows: 21,
    cols: 21,
    seed: 950,
    difficulty: 'medium',
    theme: 'sunset',
    widenPasses: 0,
    loopCount: 1,
  },
  {
    id: 8,
    name: 'Tide Pools',
    rows: 21,
    cols: 21,
    seed: 2750,
    difficulty: 'medium',
    theme: 'tide',
    widenPasses: 0,
    loopCount: 2,
  },
  {
    id: 9,
    name: 'Crystal Cave',
    rows: 21,
    cols: 23,
    seed: 1952,
    difficulty: 'medium',
    theme: 'crystal',
    widenPasses: 0,
    loopCount: 2,
  },
  {
    id: 10,
    name: 'Lava Labyrinth',
    rows: 23,
    cols: 23,
    seed: 1064,
    difficulty: 'medium',
    theme: 'lava',
    widenPasses: 0,
    loopCount: 2,
  },
  {
    id: 11,
    name: 'Storm Spiral',
    rows: 23,
    cols: 23,
    seed: 2549,
    difficulty: 'hard',
    theme: 'storm',
    widenPasses: 0,
    loopCount: 3,
  },
  {
    id: 12,
    name: 'Aurora Alley',
    rows: 23,
    cols: 25,
    seed: 5450,
    difficulty: 'hard',
    theme: 'aurora',
    widenPasses: 0,
    loopCount: 3,
  },
  {
    id: 13,
    name: 'Moon Maze',
    rows: 25,
    cols: 25,
    seed: 1559,
    difficulty: 'hard',
    theme: 'moon',
    widenPasses: 0,
    loopCount: 3,
  },
  {
    id: 14,
    name: 'Dragon Den',
    rows: 25,
    cols: 25,
    seed: 6419,
    difficulty: 'hard',
    theme: 'dragon',
    widenPasses: 0,
    loopCount: 4,
  },
  {
    id: 15,
    name: 'Galaxy Gate',
    rows: 25,
    cols: 25,
    seed: 4337,
    difficulty: 'hard',
    theme: 'galaxy',
    widenPasses: 0,
    loopCount: 4,
  },
  {
    id: 16,
    name: 'Champion Cup',
    rows: 25,
    cols: 25,
    seed: 5699,
    difficulty: 'hard',
    theme: 'champion',
    widenPasses: 0,
    loopCount: 5,
  },
];

export function getLevel(id: number): LevelConfig | undefined {
  return LEVELS.find((l) => l.id === id);
}
