import type { LevelConfig } from '../types';

export const DEFAULT_BONUS_SECONDS = 40;

/** Soft ~40s bonus; the biggest late boards get a few extra seconds. */
export function bonusSecondsForLevel(level: LevelConfig): number {
  if (typeof level.bonusSeconds === 'number' && level.bonusSeconds > 0) {
    return level.bonusSeconds;
  }
  const cells = level.rows * level.cols;
  if (cells >= 31 * 31) return 50;
  if (cells >= 800) return 45;
  return DEFAULT_BONUS_SECONDS;
}

/**
 * 40 branchy mazes for a sharp ~7-year-old.
 *
 * Growing-tree generation (high random-pick) produces many junctions and
 * cul-de-sacs — not the old long guided corridor. Every level is
 * single-width (widenPasses: 0). Goal is the farthest cell.
 *
 * Seeds were scored for dead ends + solution-path choice points.
 * Late levels add sparse opposite-wall loops only (never open rooms).
 * Levels 1–16 stay stable so existing progress and muscle memory hold.
 */
export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Coral Cove',
    rows: 17,
    cols: 17,
    seed: 15457,
    difficulty: 'easy',
    theme: 'meadow',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 2,
    name: 'Kelp Forest',
    rows: 17,
    cols: 19,
    seed: 15345,
    difficulty: 'easy',
    theme: 'hedge',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 3,
    name: 'Bubble Bay',
    rows: 19,
    cols: 19,
    seed: 1225,
    difficulty: 'easy',
    theme: 'orchard',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 4,
    name: 'Seahorse Stream',
    rows: 19,
    cols: 21,
    seed: 3645,
    difficulty: 'easy',
    theme: 'river',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 5,
    name: 'Turtle Lagoon',
    rows: 21,
    cols: 21,
    seed: 12757,
    difficulty: 'easy',
    theme: 'forest',
    widenPasses: 0,
    loopCount: 0,
  },
  {
    id: 6,
    name: 'Crab Canyon',
    rows: 21,
    cols: 21,
    seed: 15005,
    difficulty: 'medium',
    theme: 'canyon',
    widenPasses: 0,
    loopCount: 1,
  },
  {
    id: 7,
    name: 'Sunset Reef',
    rows: 21,
    cols: 23,
    seed: 15105,
    difficulty: 'medium',
    theme: 'sunset',
    widenPasses: 0,
    loopCount: 1,
  },
  {
    id: 8,
    name: 'Tidal Treasure',
    rows: 23,
    cols: 23,
    seed: 5585,
    difficulty: 'medium',
    theme: 'tide',
    widenPasses: 0,
    loopCount: 2,
  },
  {
    id: 9,
    name: 'Crystal Cavern',
    rows: 23,
    cols: 23,
    seed: 11597,
    difficulty: 'medium',
    theme: 'crystal',
    widenPasses: 0,
    loopCount: 2,
  },
  {
    id: 10,
    name: 'Volcano Vent',
    rows: 23,
    cols: 25,
    seed: 10593,
    difficulty: 'medium',
    theme: 'lava',
    widenPasses: 0,
    loopCount: 2,
  },
  {
    id: 11,
    name: 'Stormy Seas',
    rows: 25,
    cols: 25,
    seed: 4377,
    difficulty: 'hard',
    theme: 'storm',
    widenPasses: 0,
    loopCount: 3,
  },
  {
    id: 12,
    name: 'Aurora Abyss',
    rows: 25,
    cols: 25,
    seed: 3253,
    difficulty: 'hard',
    theme: 'aurora',
    widenPasses: 0,
    loopCount: 3,
  },
  {
    id: 13,
    name: 'Moonlit Marina',
    rows: 25,
    cols: 25,
    seed: 2225,
    difficulty: 'hard',
    theme: 'moon',
    widenPasses: 0,
    loopCount: 3,
  },
  {
    id: 14,
    name: 'Dragonfish Den',
    rows: 25,
    cols: 25,
    seed: 5089,
    difficulty: 'hard',
    theme: 'dragon',
    widenPasses: 0,
    loopCount: 4,
  },
  {
    id: 15,
    name: 'Galaxy Grotto',
    rows: 25,
    cols: 25,
    seed: 761,
    difficulty: 'hard',
    theme: 'galaxy',
    widenPasses: 0,
    loopCount: 4,
  },
  {
    id: 16,
    name: 'Reef Champion',
    rows: 25,
    cols: 25,
    seed: 4157,
    difficulty: 'hard',
    theme: 'champion',
    widenPasses: 0,
    loopCount: 5,
  },
  {
    id: 17,
    name: 'Pearl Pavilion',
    rows: 23,
    cols: 27,
    seed: 7900,
    difficulty: 'hard',
    theme: 'pearl',
    widenPasses: 0,
    loopCount: 6,
    randomPick: 0.64,
  },
  {
    id: 18,
    name: 'Shipwreck Shoals',
    rows: 27,
    cols: 23,
    seed: 6887,
    difficulty: 'hard',
    theme: 'shipwreck',
    widenPasses: 0,
    loopCount: 6,
    randomPick: 0.64,
  },
  {
    id: 19,
    name: 'Glowfin Gardens',
    rows: 25,
    cols: 27,
    seed: 7872,
    difficulty: 'hard',
    theme: 'bioluminescent',
    widenPasses: 0,
    loopCount: 7,
    randomPick: 0.66,
  },
  {
    id: 20,
    name: 'Iceberg Inlet',
    rows: 27,
    cols: 25,
    seed: 8635,
    difficulty: 'hard',
    theme: 'iceberg',
    widenPasses: 0,
    loopCount: 7,
    randomPick: 0.66,
  },
  {
    id: 21,
    name: 'Mangrove Maze',
    rows: 23,
    cols: 29,
    seed: 8066,
    difficulty: 'hard',
    theme: 'mangrove',
    widenPasses: 0,
    loopCount: 8,
    randomPick: 0.68,
  },
  {
    id: 22,
    name: 'Whirlpool Watch',
    rows: 29,
    cols: 23,
    seed: 6979,
    difficulty: 'hard',
    theme: 'whirlpool',
    widenPasses: 0,
    loopCount: 8,
    randomPick: 0.68,
  },
  {
    id: 23,
    name: 'Treasure Hold',
    rows: 27,
    cols: 27,
    seed: 4190,
    difficulty: 'legend',
    theme: 'treasure',
    widenPasses: 0,
    loopCount: 9,
    randomPick: 0.7,
  },
  {
    id: 24,
    name: 'Smoker Stacks',
    rows: 25,
    cols: 29,
    seed: 8579,
    difficulty: 'legend',
    theme: 'smoker',
    widenPasses: 0,
    loopCount: 10,
    randomPick: 0.7,
  },
  {
    id: 25,
    name: 'Oyster Opera',
    rows: 29,
    cols: 25,
    seed: 4236,
    difficulty: 'legend',
    theme: 'pearl',
    widenPasses: 0,
    loopCount: 11,
    randomPick: 0.72,
  },
  {
    id: 26,
    name: 'Ghost Galleon',
    rows: 25,
    cols: 31,
    seed: 4185,
    difficulty: 'legend',
    theme: 'shipwreck',
    widenPasses: 0,
    loopCount: 12,
    randomPick: 0.72,
  },
  {
    id: 27,
    name: 'Lanternfish Lair',
    rows: 31,
    cols: 25,
    seed: 5392,
    difficulty: 'legend',
    theme: 'bioluminescent',
    widenPasses: 0,
    loopCount: 13,
    randomPick: 0.74,
  },
  {
    id: 28,
    name: 'Frostfin Fjord',
    rows: 27,
    cols: 29,
    seed: 5711,
    difficulty: 'legend',
    theme: 'iceberg',
    widenPasses: 0,
    loopCount: 14,
    randomPick: 0.74,
  },
  {
    id: 29,
    name: 'Rooted Reef',
    rows: 29,
    cols: 27,
    seed: 8620,
    difficulty: 'legend',
    theme: 'mangrove',
    widenPasses: 0,
    loopCount: 15,
    randomPick: 0.75,
  },
  {
    id: 30,
    name: 'Maelstrom Mile',
    rows: 29,
    cols: 29,
    seed: 7533,
    difficulty: 'legend',
    theme: 'whirlpool',
    widenPasses: 0,
    loopCount: 16,
    randomPick: 0.75,
  },
  {
    id: 31,
    name: 'Doubloon Dock',
    rows: 27,
    cols: 31,
    seed: 9554,
    difficulty: 'legend',
    theme: 'treasure',
    widenPasses: 0,
    loopCount: 17,
    randomPick: 0.76,
  },
  {
    id: 32,
    name: 'Vent Valley',
    rows: 31,
    cols: 27,
    seed: 5285,
    difficulty: 'legend',
    theme: 'smoker',
    widenPasses: 0,
    loopCount: 18,
    randomPick: 0.76,
  },
  {
    id: 33,
    name: 'Nacre Narrows',
    rows: 29,
    cols: 31,
    seed: 33281,
    difficulty: 'legend',
    theme: 'pearl',
    widenPasses: 0,
    loopCount: 19,
    randomPick: 0.77,
  },
  {
    id: 34,
    name: 'Cannon Cove',
    rows: 31,
    cols: 29,
    seed: 4147,
    difficulty: 'legend',
    theme: 'shipwreck',
    widenPasses: 0,
    loopCount: 20,
    randomPick: 0.77,
  },
  {
    id: 35,
    name: 'Midnight Glow',
    rows: 31,
    cols: 31,
    seed: 8758,
    difficulty: 'legend',
    theme: 'bioluminescent',
    widenPasses: 0,
    loopCount: 20,
    randomPick: 0.78,
  },
  {
    id: 36,
    name: 'Glacier Gate',
    rows: 29,
    cols: 31,
    seed: 4785,
    difficulty: 'legend',
    theme: 'iceberg',
    widenPasses: 0,
    loopCount: 21,
    randomPick: 0.78,
  },
  {
    id: 37,
    name: 'Tangled Tide',
    rows: 31,
    cols: 29,
    seed: 4882,
    difficulty: 'legend',
    theme: 'mangrove',
    widenPasses: 0,
    loopCount: 22,
    randomPick: 0.79,
  },
  {
    id: 38,
    name: 'Vortex Vault',
    rows: 31,
    cols: 31,
    seed: 9715,
    difficulty: 'legend',
    theme: 'whirlpool',
    widenPasses: 0,
    loopCount: 22,
    randomPick: 0.79,
  },
  {
    id: 39,
    name: "Kraken's Keep",
    rows: 31,
    cols: 31,
    seed: 5292,
    difficulty: 'legend',
    theme: 'treasure',
    widenPasses: 0,
    loopCount: 23,
    randomPick: 0.8,
  },
  {
    id: 40,
    name: 'Abyss Crown',
    rows: 31,
    cols: 31,
    seed: 5115,
    difficulty: 'legend',
    theme: 'smoker',
    widenPasses: 0,
    loopCount: 24,
    randomPick: 0.8,
  },
];

export function getLevel(id: number): LevelConfig | undefined {
  return LEVELS.find((l) => l.id === id);
}
